-- Skin Analysis Results Database Schema
-- Store AI-powered skin analysis results from 8-mode detection system

-- Create skin_analyses table
CREATE TABLE IF NOT EXISTS skin_analyses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  booking_id VARCHAR(50) REFERENCES bookings(id) ON DELETE SET NULL,
  
  -- Image information
  image_url TEXT NOT NULL,
  image_thumbnail_url TEXT,
  original_filename VARCHAR(255),
  image_width INTEGER,
  image_height INTEGER,
  
  -- Analysis timestamp
  analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  analysis_version VARCHAR(20) DEFAULT '1.0.0',
  
  -- Overall scores (0-100)
  overall_score NUMERIC(5, 2),
  skin_health_grade VARCHAR(2), -- A+, A, B+, B, C+, C, D, F
  
  -- Individual mode results (0-100 scores)
  spots_score NUMERIC(5, 2),
  wrinkles_score NUMERIC(5, 2),
  texture_score NUMERIC(5, 2),
  pores_score NUMERIC(5, 2),
  uv_spots_score NUMERIC(5, 2),
  brown_spots_score NUMERIC(5, 2),
  red_areas_score NUMERIC(5, 2),
  porphyrins_score NUMERIC(5, 2),
  
  -- Detection counts
  spots_count INTEGER DEFAULT 0,
  wrinkles_count INTEGER DEFAULT 0,
  pores_count INTEGER DEFAULT 0,
  uv_spots_count INTEGER DEFAULT 0,
  brown_spots_count INTEGER DEFAULT 0,
  red_areas_percentage NUMERIC(5, 2) DEFAULT 0,
  porphyrins_count INTEGER DEFAULT 0,
  
  -- Severity levels (low, moderate, high, severe)
  spots_severity VARCHAR(20),
  wrinkles_severity VARCHAR(20),
  texture_severity VARCHAR(20),
  pores_severity VARCHAR(20),
  uv_spots_severity VARCHAR(20),
  brown_spots_severity VARCHAR(20),
  red_areas_severity VARCHAR(20),
  porphyrins_severity VARCHAR(20),
  
  -- Detailed results (JSON from AI service)
  spots_detections JSONB,
  wrinkles_detections JSONB,
  texture_analysis JSONB,
  pores_detections JSONB,
  uv_spots_detections JSONB,
  brown_spots_detections JSONB,
  red_areas_analysis JSONB,
  porphyrins_detections JSONB,
  
  -- Visualization URLs (generated overlay images)
  visualization_url TEXT, -- Full multi-mode visualization
  spots_viz_url TEXT,
  wrinkles_viz_url TEXT,
  texture_viz_url TEXT,
  pores_viz_url TEXT,
  uv_spots_viz_url TEXT,
  brown_spots_viz_url TEXT,
  red_areas_viz_url TEXT,
  porphyrins_viz_url TEXT,
  
  -- Processing metadata
  processing_time_ms INTEGER,
  ai_model_version VARCHAR(50) DEFAULT 'cv-based-v1.0',
  
  -- Skin type and concerns (auto-detected or user-provided)
  skin_type VARCHAR(20), -- 'oily', 'dry', 'combination', 'sensitive', 'normal'
  primary_concerns TEXT[], -- ['acne', 'aging', 'pigmentation', 'redness', 'texture']
  
  -- Recommendations (generated by AI)
  recommendations JSONB, -- {treatments: [], products: [], lifestyle: []}
  
  -- Status
  status VARCHAR(20) DEFAULT 'completed', -- 'processing', 'completed', 'failed'
  error_message TEXT,
  
  -- Metadata
  notes TEXT,
  is_baseline BOOLEAN DEFAULT false, -- First analysis for comparison
  is_verified BOOLEAN DEFAULT false, -- Verified by dermatologist
  verified_by UUID REFERENCES auth.users(id),
  verified_at TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create analysis comparisons table (link two analyses for progress tracking)
CREATE TABLE IF NOT EXISTS analysis_comparisons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Analyses being compared
  before_analysis_id UUID NOT NULL REFERENCES skin_analyses(id) ON DELETE CASCADE,
  after_analysis_id UUID NOT NULL REFERENCES skin_analyses(id) ON DELETE CASCADE,
  
  -- Time between analyses
  days_between INTEGER,
  
  -- Improvement percentages (-100 to +100)
  spots_improvement NUMERIC(6, 2),
  wrinkles_improvement NUMERIC(6, 2),
  texture_improvement NUMERIC(6, 2),
  pores_improvement NUMERIC(6, 2),
  uv_spots_improvement NUMERIC(6, 2),
  brown_spots_improvement NUMERIC(6, 2),
  red_areas_improvement NUMERIC(6, 2),
  porphyrins_improvement NUMERIC(6, 2),
  overall_improvement NUMERIC(6, 2),
  
  -- Change in counts
  spots_change INTEGER,
  wrinkles_change INTEGER,
  pores_change INTEGER,
  uv_spots_change INTEGER,
  brown_spots_change INTEGER,
  
  -- Comparison visualization
  comparison_viz_url TEXT, -- Side-by-side or overlay comparison
  
  -- Report
  report_generated BOOLEAN DEFAULT false,
  report_url TEXT,
  report_data JSONB,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX idx_skin_analyses_user ON skin_analyses(user_id);
CREATE INDEX idx_skin_analyses_booking ON skin_analyses(booking_id);
CREATE INDEX idx_skin_analyses_analyzed_at ON skin_analyses(analyzed_at DESC);
CREATE INDEX idx_skin_analyses_status ON skin_analyses(status);
CREATE INDEX idx_skin_analyses_is_baseline ON skin_analyses(is_baseline) WHERE is_baseline = true;
CREATE INDEX idx_skin_analyses_overall_score ON skin_analyses(overall_score DESC);

CREATE INDEX idx_analysis_comparisons_user ON analysis_comparisons(user_id);
CREATE INDEX idx_analysis_comparisons_before ON analysis_comparisons(before_analysis_id);
CREATE INDEX idx_analysis_comparisons_after ON analysis_comparisons(after_analysis_id);

-- Create function to calculate overall score
CREATE OR REPLACE FUNCTION calculate_overall_skin_score(
  p_spots NUMERIC,
  p_wrinkles NUMERIC,
  p_texture NUMERIC,
  p_pores NUMERIC,
  p_uv_spots NUMERIC,
  p_brown_spots NUMERIC,
  p_red_areas NUMERIC,
  p_porphyrins NUMERIC
) RETURNS NUMERIC AS $$
BEGIN
  -- Weighted average: texture and spots are most important
  RETURN ROUND(
    (p_texture * 0.20 +
     p_spots * 0.15 +
     p_wrinkles * 0.15 +
     p_pores * 0.12 +
     p_uv_spots * 0.13 +
     p_brown_spots * 0.10 +
     p_red_areas * 0.10 +
     p_porphyrins * 0.05),
    2
  );
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Create function to determine skin health grade
CREATE OR REPLACE FUNCTION get_skin_health_grade(score NUMERIC) RETURNS VARCHAR AS $$
BEGIN
  IF score >= 95 THEN RETURN 'A+';
  ELSIF score >= 90 THEN RETURN 'A';
  ELSIF score >= 85 THEN RETURN 'B+';
  ELSIF score >= 80 THEN RETURN 'B';
  ELSIF score >= 75 THEN RETURN 'C+';
  ELSIF score >= 70 THEN RETURN 'C';
  ELSIF score >= 60 THEN RETURN 'D';
  ELSE RETURN 'F';
  END IF;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Create trigger to auto-calculate overall score
CREATE OR REPLACE FUNCTION update_skin_analysis_scores()
RETURNS TRIGGER AS $$
BEGIN
  -- Calculate overall score if individual scores exist
  IF NEW.spots_score IS NOT NULL THEN
    NEW.overall_score := calculate_overall_skin_score(
      COALESCE(NEW.spots_score, 0),
      COALESCE(NEW.wrinkles_score, 0),
      COALESCE(NEW.texture_score, 0),
      COALESCE(NEW.pores_score, 0),
      COALESCE(NEW.uv_spots_score, 0),
      COALESCE(NEW.brown_spots_score, 0),
      COALESCE(NEW.red_areas_score, 0),
      COALESCE(NEW.porphyrins_score, 0)
    );
    
    -- Calculate grade
    NEW.skin_health_grade := get_skin_health_grade(NEW.overall_score);
  END IF;
  
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_skin_analysis_scores
BEFORE INSERT OR UPDATE ON skin_analyses
FOR EACH ROW
EXECUTE FUNCTION update_skin_analysis_scores();

-- Enable Row Level Security (RLS)
ALTER TABLE skin_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_comparisons ENABLE ROW LEVEL SECURITY;

-- RLS Policies for skin_analyses
CREATE POLICY "Users can view their own analyses"
  ON skin_analyses FOR SELECT
  USING (auth.uid() = user_id OR auth.jwt()->>'role' = 'admin');

CREATE POLICY "Users can create their own analyses"
  ON skin_analyses FOR INSERT
  WITH CHECK (auth.uid() = user_id OR auth.jwt()->>'role' = 'admin');

CREATE POLICY "Users can update their own analyses"
  ON skin_analyses FOR UPDATE
  USING (auth.uid() = user_id OR auth.jwt()->>'role' = 'admin');

CREATE POLICY "Admins can do anything with analyses"
  ON skin_analyses FOR ALL
  USING (auth.jwt()->>'role' = 'admin');

-- RLS Policies for analysis_comparisons
CREATE POLICY "Users can view their own comparisons"
  ON analysis_comparisons FOR SELECT
  USING (auth.uid() = user_id OR auth.jwt()->>'role' = 'admin');

CREATE POLICY "Users can create their own comparisons"
  ON analysis_comparisons FOR INSERT
  WITH CHECK (auth.uid() = user_id OR auth.jwt()->>'role' = 'admin');

CREATE POLICY "Admins can do anything with comparisons"
  ON analysis_comparisons FOR ALL
  USING (auth.jwt()->>'role' = 'admin');

-- Add comments for documentation
COMMENT ON TABLE skin_analyses IS 'AI-powered skin analysis results from 8-mode VISIA-style detection system';
COMMENT ON TABLE analysis_comparisons IS 'Track progress by comparing two skin analyses over time';

COMMENT ON COLUMN skin_analyses.overall_score IS 'Weighted average of all 8 mode scores (0-100)';
COMMENT ON COLUMN skin_analyses.skin_health_grade IS 'Letter grade from A+ to F based on overall score';
COMMENT ON COLUMN skin_analyses.is_baseline IS 'Mark as first/baseline analysis for progress tracking';
COMMENT ON COLUMN skin_analyses.visualization_url IS 'URL to multi-mode overlay visualization image';
COMMENT ON COLUMN skin_analyses.recommendations IS 'AI-generated treatment and product recommendations';

COMMENT ON COLUMN analysis_comparisons.overall_improvement IS 'Overall improvement percentage (positive = better, negative = worse)';

-- Grant permissions
GRANT SELECT, INSERT, UPDATE ON skin_analyses TO authenticated;
GRANT SELECT, INSERT ON analysis_comparisons TO authenticated;
GRANT ALL ON skin_analyses TO service_role;
GRANT ALL ON analysis_comparisons TO service_role;
